using Microsoft.EntityFrameworkCore;

namespace Data.Context
{
    /// <summary>
    /// Crea la tabla de auditoría si falta.
    ///
    /// La aplicación construye el esquema con <see cref="RelationalDatabaseCreatorExtensions.EnsureCreated"/>,
    /// que solo actúa cuando la base NO existe. En una base creada antes de que
    /// existiera <see cref="Models.AuditLog"/>, EnsureCreated no hace nada y la tabla
    /// nunca aparece: el interceptor de auditoría intenta insertar en ella y
    /// PostgreSQL responde <c>42P01: relation "AuditLogs" does not exist</c>.
    ///
    /// Esto es DDL a mano porque el proyecto no usa migraciones. Si en algún momento
    /// se adoptan, este archivo sobra: hay que reemplazarlo por una migración y
    /// mantener el esquema en un solo lugar.
    ///
    /// El script es idempotente: se puede ejecutar en cada arranque sin efecto.
    /// Debe mantenerse en sintonía con <see cref="Configurations.AuditLogConfiguration"/>.
    /// </summary>
    public static class AuditLogSchema
    {
        private const string Ddl = """
            CREATE TABLE IF NOT EXISTS "AuditLogs" (
                "Id"             bigint GENERATED BY DEFAULT AS IDENTITY,
                "Timestamp"      timestamp with time zone NOT NULL,
                "UserId"         integer NULL,
                "CompanyId"      integer NULL,
                "Action"         character varying(50) NOT NULL,
                "EntityType"     character varying(100) NOT NULL,
                "EntityId"       character varying(100) NOT NULL,
                "OldValues"      jsonb NULL,
                "NewValues"      jsonb NULL,
                "ChangedColumns" character varying(2000) NULL,
                "TraceId"        character varying(64) NULL,
                "Application"    character varying(100) NOT NULL,
                "IpAddress"      character varying(64) NULL,
                CONSTRAINT "PK_AuditLogs" PRIMARY KEY ("Id")
            );

            CREATE INDEX IF NOT EXISTS "IX_AuditLogs_Timestamp"
                ON "AuditLogs" ("Timestamp");
            CREATE INDEX IF NOT EXISTS "IX_AuditLogs_CompanyId_Timestamp"
                ON "AuditLogs" ("CompanyId", "Timestamp");
            CREATE INDEX IF NOT EXISTS "IX_AuditLogs_EntityType_EntityId"
                ON "AuditLogs" ("EntityType", "EntityId");
            CREATE INDEX IF NOT EXISTS "IX_AuditLogs_UserId"
                ON "AuditLogs" ("UserId");
            CREATE INDEX IF NOT EXISTS "IX_AuditLogs_TraceId"
                ON "AuditLogs" ("TraceId");
            """;

        /// <summary>
        /// Devuelve true si la tabla ya existía o se creó correctamente.
        /// No lanza: si falla, la aplicación arranca igual y la auditoría queda
        /// sin escribir, que es preferible a no poder arrancar.
        /// </summary>
        public static bool EnsureExists(AppDbContext context)
        {
            try
            {
                context.Database.ExecuteSqlRaw(Ddl);
                return true;
            }
            catch
            {
                return false;
            }
        }
    }
}
